### ISSUE TITLE
Mailbox still broken

### ISSUE THREAD

**Issue by sternschnaube** [Patbox/PolyDecorations#7]
Can't insert items.

**Comment by sternschnaube** [comment]
Failed to save chunk 366,173
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1273.method_5474(net.minecraft.class_2487)" because "this.lock" is null
	at eu.pb4.factorytools.api.block.entity.LockableBlockEntity.method_11007(LockableBlockEntity.java:58) ~[factorytools-0.2.0+1.20.6-6d885af0e7b118a4.jar:?]
	at eu.pb4.polydecorations.block.item.MailboxBlockEntity.method_11007(MailboxBlockEntity.java:56) ~[polydecorations-0.3.0+1.20.6.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:94) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.redirect$zjp000$c2me-threading-chunkio$onChunkGetPackedBlockEntityNbt(class_2852.java:2609) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:330) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:843) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:807) ~[server-intermediary.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1719) ~[fastutil-8.5.12.jar:?]
	at net.minecraft.class_3898.method_17242(class_3898.java:461) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_17298(class_3215.java:304) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_14176(class_3218.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:550) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:574) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[18:25:51] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 7714ms or 154 ticks behind
[18:25:52] [Server thread/ERROR]: Failed to save chunk 366,173
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1273.method_5474(net.minecraft.class_2487)" because "this.lock" is null
	at eu.pb4.factorytools.api.block.entity.LockableBlockEntity.method_11007(LockableBlockEntity.java:58) ~[factorytools-0.2.0+1.20.6-6d885af0e7b118a4.jar:?]
	at eu.pb4.polydecorations.block.item.MailboxBlockEntity.method_11007(MailboxBlockEntity.java:56) ~[polydecorations-0.3.0+1.20.6.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:94) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.redirect$zjp000$c2me-threading-chunkio$onChunkGetPackedBlockEntityNbt(class_2852.java:2609) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:330) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:843) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:807) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.c2me$runOneChunkAutoSave(class_3898.java:18499) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.modifyReturnValue$zik000$c2me-opts-scheduling$postRunTask(MinecraftServer.java:23071) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:835) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:817) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:792) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by Patbox** [comment]
You are still on 0.3.0, the fix is on 0.3.1

**Comment by sternschnaube** [comment]
Sorry 😓
